services:
    backend:
        build: .
        image: main-api
        env_file:
            - .env
        ports:
            - "${API_PORT}:${API_PORT}"
        volumes:
            - ./creneaux.json:/app/creneaux.json
